name: opentool_daemon
description: A HTTP Daemon Server to manage native OpenTool Servers.
version: 0.1.0
repository: https://github.com/opentool-hub/opentool-daemon

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  hive: ^2.2.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  dio: ^5.8.0+1
  crypto: ^3.0.6
  opentool_dart:
    path: ../opentool-dart

dev_dependencies:
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0